# Generated by Django 4.0.4 on 2022-04-28 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='registro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.registro'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.sensor'),
        ),
    ]
