# Generated by Django 4.0.4 on 2022-05-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_imagen_nombre_alter_imagen_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periferico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('Ventilador', 'Ventilador'), ('Led', 'Led')], default='Led', max_length=11)),
            ],
        ),
    ]
