# Generated by Django 4.0.4 on 2022-05-04 17:10

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_periferico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periferico',
            old_name='tipo',
            new_name='tipo_periferico',
        ),
        migrations.AddField(
            model_name='sensor',
            name='r_number',
            field=models.CharField(blank=True, default=app.utils.create_new_ref_number, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tipo_sensor',
            field=models.CharField(choices=[('Puerta', 'Puerta'), ('Camara', 'Camara')], default='Puerta', max_length=11),
        ),
    ]
