# Generated by Django 4.0.4 on 2022-05-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_tipo_periferico_tipo_periferico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periferico',
            name='tipo_periferico',
        ),
        migrations.AddField(
            model_name='periferico',
            name='tipo',
            field=models.CharField(choices=[('Ventilador', 'Ventilador'), ('Led', 'Led')], default='Led', max_length=11),
        ),
    ]
