# Generated by Django 4.0.4 on 2022-05-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_periferico_tipo_periferico_periferico_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periferico',
            old_name='tipo',
            new_name='tipo_periferico',
        ),
    ]
