# Generated by Django 4.0.4 on 2022-05-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_registro_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='image',
            new_name='imagen',
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
