# Generated by Django 4.0.4 on 2022-05-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_image_registro_imagen_delete_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Periferico',
            new_name='Dispositivo',
        ),
    ]
