# Generated by Django 4.0.4 on 2022-05-06 16:19

import app.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_rename_periferico_dispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='r_number',
            field=models.CharField(blank=True, default=app.utils.create_new_ref_number, editable=False, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
